gk/gk/urls.py
from django.contrib import admin
from django.urls import path
import gkapp.views as views

urlpatterns = [
    path('', views.homepage, name="homepage"),
    path('get-room-categories/<int:guesthouse_id>/', views.get_room_categories, name='get_room_categories'),
    path('get-guest-categories/<int:room_category_id>/', views.get_guest_categories, name='get_guest_categories'),
    path('customer/login', views.customer_login, name="customer_login"),
    path('customer/signup', views.customer_signup.as_view(), name="customer_signup"),
    path('customer/customer_dash', views.customer_dash, name="customer_dash"),
    path('customer/request', views.request, name="request"),
    path('employee/approval', views.approval, name="approval"),
    path('employee/login', views.employee_login, name="employee_login"),
    path('employee/signup', views.employee_signup.as_view(), name="employee_signup"),
    path('employee/employee_dash', views.employee_dash, name="employee_dash"),
    path('employee/guesthouseshw', views.guesthouseshw, name="guesthouseshw"),
    path('employee/roomrates', views.roomrates, name="roomrates"),
    path('employee/addguesthouse', views.addguesthouse, name="addguesthouse"),
    path('employee/viewroomcategories', views.viewroomcategories, name="viewroomcategories"),
    path('employee/addroomcategories', views.addroomcategories, name="addroomcategories"),
    path('employee/viewguestcategories', views.viewguestcategories, name="viewguestcategories"),
    path('employee/addguestcategories', views.addguestcategories, name="addguestcategories"),
    path('employee/viewroomrates', views.viewroomrates, name="viewroomrates"),
    path('employee/addroomrates', views.addroomrates, name="addroomrates"),
    path('employee/viewrooms', views.viewrooms, name="viewrooms"),
    path('employee/addrooms', views.addrooms, name="addrooms"),
    path('employee/addbooking', views.addbooking, name="addbooking"),
    path('employee/viewbooking', views.viewbooking, name="viewbooking"),
    path('logout/',views.logout_view, name='logout'),
    path('employee/requestshow',views.show, name='show'),
    path('admin/', admin.site.urls),
    path('employee/rr', views.create_room_rate, name='create_room_rate'),
    path('booking_procedure', views.booking_procedure, name='booking_procedure'),
    path('images', views.images, name='images'),
    path('contact_us', views.contact_us, name='contact_us'),
    path('committee', views.committee, name='committee'),
    path('imp_info', views.imp_info, name='imp_info'),
]

gk/gkapp/models.py
# Create your models here.
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    is_customer = models.BooleanField(default=False)
    is_employee = models.BooleanField(default=False)

    def __str__(self):
        return (self.username)


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    first_name = models.CharField(max_length=100, unique=False,null=True)
    last_name = models.CharField(max_length=100, unique=False, null=True)
    address = models.CharField(max_length=100, unique=False, null=True)
    country = models.CharField(max_length=100, unique=False, null=True)
    state = models.CharField(max_length=100, unique=False, null=True)
    city = models.CharField(max_length=100, unique=False, null=True)
    mobile_no = models.CharField(max_length=100, unique=False, null=True)
    aadhar_no = models.CharField(max_length=100, unique=False, null=True)

class Employee(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)


class GuestHouses(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class RoomCategories(models.Model):
    guesthouse_name = models.ForeignKey(GuestHouses, on_delete=models.CASCADE)
    room_cat = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.room_cat


class GuestCategories(models.Model):
    room_category = models.ForeignKey(RoomCategories, on_delete=models.CASCADE)
    guestcategory_name = models.CharField(max_length=100, unique=False)

    def __str__(self):
        return self.guestcategory_name

class RoomRates(models.Model):
    room_category_id = models.ForeignKey(RoomCategories, on_delete=models.CASCADE)
    guest_category = models.ForeignKey(GuestCategories, on_delete=models.CASCADE)
    rate = models.FloatField(null=True)

    def __str__(self):
        return str(self.rate)


class Request(models.Model):
    name = models.CharField(max_length=100, unique=False)
    email = models.EmailField(max_length=100)
    mob = models.IntegerField(null=True)
    id_proof_no = models.IntegerField(null=True)
    no_of_persons = models.IntegerField(null=True)
    no_of_rooms = models.IntegerField(null=True)
    checkin = models.DateField(blank=True, null=True)
    checkout = models.DateField(blank=True, null=True)
    request_datetime = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.name)

    class Meta:
        db_table = "request"


class Approval(models.Model):
    request= models.ForeignKey(Request, on_delete=models.CASCADE)
    is_approved = models.BooleanField(default=False)
    approval_date=models.DateTimeField(auto_now=True)
    approved_by=models.ForeignKey(Employee, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.approved_by)

    class Meta:
        db_table = "approval"

class Rooms(models.Model):
    GuestHouses=models.ForeignKey(GuestHouses, on_delete=models.CASCADE)
    RoomCategories=models.ForeignKey(RoomCategories, on_delete=models.CASCADE)
    is_available=models.BooleanField(default=False)
    room_no=models.CharField(max_length=100, unique=False)
    room_desc=models.CharField(max_length=100, unique=False)
    room_capacity=models.IntegerField()

    def __str__(self):
        return self.room_no
    class Meta:
        db_table = "rooms"

class Reservation(models.Model):
    GuestHouses = models.ForeignKey(GuestHouses, on_delete=models.CASCADE)
    RoomCategories = models.ForeignKey(RoomCategories, on_delete=models.CASCADE)
    guest_category = models.ForeignKey(GuestCategories, on_delete=models.CASCADE, null=True)
    rooms = models.ForeignKey(Rooms, on_delete=models.CASCADE)
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    room_rate = models.ForeignKey(RoomRates, on_delete=models.CASCADE)
    checkin = models.DateField(blank=True, null=True)
    checkout = models.DateField(blank=True, null=True)
    no_of_days = models.IntegerField()
    total_amount = models.FloatField()

    class Meta:
        db_table = "reservation"

gk/gkapp/views.py
from django.http import JsonResponse, HttpResponse, HttpResponseRedirect
from .models import GuestHouses, RoomCategories, GuestCategories, RoomRates,Rooms,Reservation
from django.contrib.auth import login, logout, authenticate
from django.views.generic import CreateView
from .form import *
from .models import User
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404

def homepage(request):
    guesthouses = GuestHouses.objects.all()
    room_categories = RoomCategories.objects.none()
    guest_categories = GuestCategories.objects.none()
    room_rates = []

    if request.method == "POST":
        guesthouse_id = request.POST.get("guesthouse")
        room_category_id = request.POST.get("room_category")
        guest_category_id = request.POST.get("guest_category")

        if guesthouse_id:
            room_categories = RoomCategories.objects.filter(
                guesthouse_name_id=guesthouse_id
            )
            if room_category_id:
                guest_categories = GuestCategories.objects.filter(
                    room_category_id=room_category_id
                )
                if guest_category_id:
                    room_rates = RoomRates.objects.filter(
                        room_category_id=room_category_id,
                        guest_category_id=guest_category_id,
                    )

    return render(
        request,
        "index.html",
        {
            "guesthouses": guesthouses,
            "room_categories": room_categories,
            "guest_categories": guest_categories,
            "room_rates": room_rates,
        },
    )


def get_room_categories(request, guesthouse_id):
    room_categories = RoomCategories.objects.filter(
        guesthouse_name_id=guesthouse_id
    ).values("id", "room_cat")
    return JsonResponse({"options": list(room_categories)})


def get_guest_categories(request, room_category_id):
    guest_categories = GuestCategories.objects.filter(
        room_category_id=room_category_id
    ).values("id", "guestcategory_name")
    return JsonResponse({"options": list(guest_categories)})



class customer_signup(CreateView):
    model = User
    form_class = CustomerSignUpForm
    template_name = "../templates/customer/customer_signup.html"

    def form_valid(self, form):
        messages.success(self.request, "Account created successfully!!")
        user = form.save()
        return redirect("customer_login")


class employee_signup(CreateView):
    model = User
    form_class = EmployeeSignUpForm
    template_name = "../templates/employee/employee_signup.html"

    def form_valid(self, form):
        user = form.save()
        messages.success(self.request, "Account created successfully!!")
        return redirect("employee_login")


def customer_login(request):
    if request.user.is_authenticated:
        return redirect("/")
    elif request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_employee:
                    messages.error(
                        request, "You do not have permission to access this page."
                    )
                    return redirect("/customer_login")
                else:
                    login(request, user)
                    return redirect("/")
            else:
                messages.error(request, "Invalid username or password")
        else:
            messages.error(request, "Invalid username or password")
    return render(
        request, "customer/customer_login.html", context={"form": AuthenticationForm()}
    )


def employee_login(request):
    if request.user.is_authenticated:
        return redirect("/")
    elif request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_customer:
                    messages.error(
                        request, "You do not have permission to access this page."
                    )
                    return redirect("employee_login")
                else:
                    login(request, user)
                    return redirect("/")
            else:
                messages.error(request, "Invalid username or password")
        else:
            messages.error(request, "Invalid username or password")
    return render(
        request, "employee/employee_login.html", context={"form": AuthenticationForm()}
    )


def logout_view(request):
    logout(request)
    return redirect("/")


@login_required
def customer_dash(request):
    if request.user.is_customer == False:
        return HttpResponse('Access Denied')
    return render(request, "customer/customer_dash.html")

@login_required(login_url='/')
def employee_dash(request):
    if not request.user.is_employee:
        return redirect("employee_login")
    return render(request, "employee/employee_dash.html")


def guesthouseshw(request):
    employees = GuestHouses.objects.all()
    return render(request, "employee/guesthouseshw.html", {'employees': employees})


@login_required
def request(request):
    if request.user.is_customer == False:
        messages.error(request, "Your are not eligible for login here .Please create or login as a customer to access this page ")
        return redirect("customer_login")
    if request.method == "POST":
        form = RequestForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                messages.success(request, "Your Booking Request Has beeb submitted Successfully")
                return redirect('/')
            except:
                pass
    else:
        form = RequestForm()
    return render(request,'customer/request.html',{'form':form})

def approval(request):
    if request.method == "POST":
        form = ApprovalForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                messages.success(request, "Data inserted successfully")
            except:
                pass
    else:
        form = ApprovalForm()
    return render(request,'employee/approval.html',{'form':form})
def roomrates(request):
    stu1 = RateForm()
    return render(request, "employee/roomrates.html", {"form": stu1})


def create_room_rate(request):
    if request.method == 'POST':
        form = RoomRateForm(request.POST)
        if form.is_valid():
            form.save()
    else:
        form = RoomRateForm()

    return render(request, 'employee/rr.html', {'form': form})

def addguesthouse(request):
    if request.method == 'POST':
        form = GuesthouseForm(request.POST)
        if form.is_valid():
            form.save()
    else:
        form = GuesthouseForm()

    return render(request, 'employee/addguesthouse.html', {'form': form})

def addroomcategories(request):
    if request.method == 'POST':
        form = RoomCategoriesForm(request.POST)
        if form.is_valid():
            form.save()
    else:
        form = RoomCategoriesForm()

    return render(request, 'employee/addroomcategories.html', {'form': form})

def show(request):
    employees = Request.objects.all()
    return render(request,"employee/requestshow.html",{'employees':employees})

def viewroomcategories(request):
    roomcategories = RoomCategories.objects.all()
    return render(request,"employee/viewroomcategories.html",{'roomcategories':roomcategories})

def addguestcategories(request):
    if request.method == 'POST':
        form = GuestCategoriesForm(request.POST)
        if form.is_valid():
            form.save()
    else:
        form = GuestCategoriesForm()

    return render(request, 'employee/addguestcategories.html', {'form': form})
def viewguestcategories(request):
    guestcategories = GuestCategories.objects.all()
    return render(request,"employee/viewguestcategories.html",{'guestcategories':guestcategories})


def addroomrates(request):
    if request.method == 'POST':
        form =RateForm(request.POST)
        if form.is_valid():
            form.save()
    else:
        form = RateForm()

    return render(request, 'employee/addroomrates.html', {'form': form})


def addbooking(request):
    if request.method == 'POST':
        form1 = CustomerForm(request.POST)
        form = BookingForm(request.POST)

        if form1.is_valid() and form.is_valid():
            customer_instance = form1.save()
            booking_instance = form.save(commit=False)
            booking_instance.customer = customer_instance
            booking_instance.save()
            return redirect('booking_success')  # Replace 'booking_success' with your success URL

    else:
        form1 = CustomerForm(initial={'employee': request.user.username})
        form = BookingForm(initial={'no_of_days': 12})

    return render(request, 'employee/addbooking.html', {'form': form, 'form1': form1})
def viewbooking(request):
    reservation = Reservation.objects.all()
    return render (request,"employee/viewbooking.html",{'reservation':reservation})


def viewrooms(request):

    rooms = Rooms.objects.all()
    return render (request,"employee/viewrooms.html",{'rooms':rooms})
def addrooms(request):
    if request.method == 'POST':
        form =RoomsForm(request.POST)
        if form.is_valid():
            form.save()
    else:
        form = RoomsForm()

gk/gkapp/templates/employee/addguesthouse.html
{% extends "staffbase.html" %}
{% load static %}
{% load widget_tweaks %}
{% block content %}
   <div class="container-fluid">

                    <!-- DataTales Example -->
                    <div class="card shadow mb-4">
                        <div class="card-header py-3">
                            <h6 class="m-0 font-weight-bold text-primary">Guest House List</h6>
                        </div>
                        <div class="card-body">
                             <form action="{% url 'approval' %}" method="POST" novalidate>
                      {% csrf_token %}
                         {% for field in form.visible_fields %}
                           <div class="form-group">
                               {{ field.label_tag }}
                                  {% render_field field class="form-control" %}
<!--                                    {% if messages%}-->
<!--                                      {% for message in messages %}-->
<!--                                        <span style="color:red">{{ message }}</span>-->
<!--                                      {% endfor %}-->
<!--                                     {% endif %}-->
                         {% endfor %}
                         <br>
                             <input type="submit" value="approved" class="btn btn-block btn-primary">
                           </div>
                    </form>

                            </div>
                        </div>
                    </div>

                </div>
{% endblock content %}

gk/gkapp/templates/employee/addroomrates.html
{% extends "staffbase.html" %}
{% load static %}
{% load widget_tweaks %}
{% block content %}
   <div class="container-fluid">

                    <!-- DataTales Example -->
                    <div class="card shadow mb-4">
                        <div class="card-header py-3">
                            <h6 class="m-0 font-weight-bold text-primary">Guest House List</h6>
                        </div>
                        <div class="card-body">
                             <form action="{% url 'addroomcategories' %}" method="POST" novalidate>
                      {% csrf_token %}
                         {% for field in form.visible_fields %}
                           <div class="form-group">
                               {{ field.label_tag }}
                                  {% render_field field class="form-control" %}
                         {% endfor %}
                         <br>
                             <input type="submit" value="approved" class="btn btn-block btn-primary">
                           </div>
                    </form>

                            </div>
                        </div>
                    </div>

                </div>
{% endblock content %}

gk/gkapp/templates/employee/addrooms.html
{% extends "staffbase.html" %}
{% load static %}
{% load widget_tweaks %}
{% block content %}
   <div class="container-fluid">

                    <!-- DataTales Example -->
                    <div class="card shadow mb-4">
                        <div class="card-header py-3">
                            <h6 class="m-0 font-weight-bold text-primary">Guest House List</h6>
                        </div>
                        <div class="card-body">
                             <form action="{% url 'addrooms' %}" method="POST" novalidate>
                      {% csrf_token %}
                         {% for field in form.visible_fields %}
                           <div class="form-group">
                               {{ field.label_tag }}
                                  {% render_field field class="form-control" %}
                         {% endfor %}
                         <br>
                             <input type="submit" value="approved" class="btn btn-block btn-primary">
                           </div>
                    </form>

                            </div>
                        </div>
                    </div>

                </div>
{% endblock content %}

gk/gkapp/templates/employee/approval.html
{% extends "staffbase.html" %}
{% load static %}
{% load widget_tweaks %}
{% block content %}
     <section>
        <div class="container">
          <div class="row">
            <div class="col-md-6 mx-auto">
              <div class="card">
                <div class="card-header text-black">
                  <h2>Customer Request Approval </h2>
                </div>
                <div class="card-body">
                    <form action="{% url 'approval' %}" method="POST" novalidate>
                      {% csrf_token %}
                         {% for field in form.visible_fields %}
                           <div class="form-group">
                               {{ field.label_tag }}
                                  {% render_field field class="form-control" %}
<!--                                    {% if messages%}-->
<!--                                      {% for message in messages %}-->
<!--                                        <span style="color:red">{{ message }}</span>-->
<!--                                      {% endfor %}-->
<!--                                     {% endif %}-->
                         {% endfor %}
                         <br>
                             <input type="submit" value="approved" class="btn btn-block btn-primary">
                           </div>
                    </form>
                    <br>

                 </div>
                    </div>
                </div>
              </div>
            </div>

        </div>
      </section>
{% endblock content %}

gk/gkapp/templates/employee/city_dropdown_list_options.html
<option value="">---------</option>
{% for city in cities %}
<option value="{{ city.pk }}">{{ city.guestcategory_name }}</option>
{% endfor %}

gk/gkapp/templates/employee/edit.html
{% extends "staffbase.html" %}
{% load static %}
{% load widget_tweaks %}
{% block content %}
     <section>
        <div class="container">
          <div class="row">
            <div class="col-md-6 mx-auto">
              <div class="card">
                <div class="card-header text-black">
                  <h2>Customer Request Approval </h2>
                </div>
                <div class="card-body">
                   <form method="POST" class="post-form" action="/update/{{employee.id}}">
    {% csrf_token %}
    <div class="container">
        <br>
        {% for field in form %}
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">{{ field.label }}</label>
                <div class="col-sm-4">
                    {{ field }}
                </div>
            </div>
        {% endfor %}
        <div class="form-group row">
            <label class="col-sm-1 col-form-label"></label>
            <div class="col-sm-4">
                <button type="submit" class="btn btn-success">Update</button>
            </div>
        </div>
    </div>
</form>

                    <br>

                 </div>
                    </div>
                </div>
              </div>
            </div>

        </div>
      </section>
{% endblock content %}

gk/gkapp/templates/employee/employee_signup.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}
{% block content %}
<!--Cards starts here-->

        <!--login and signup tab starts here -->
        <section>
        <div class="container">
          <div class="row">
            <div class="col-md-6 mx-auto">
              <div class="card">
                <div class="card-header text-black">
                  <h2>Employee Signup</h2>
                </div>
                <div class="card-body">
                    <form action="{% url 'employee_signup' %}" method="POST" novalidate>
                      {% csrf_token %}
                         {% for field in form.visible_fields %}
                           <div class="form-group">
                               {{ field.label_tag }}
                                  {% render_field field class="form-control" %}
                                    {% for error in field.errors %}
                                      <span style="color:red">{{ error }}</span>
                                    {% endfor %}
                         {% endfor %}
                             <input type="submit" value="Register" class="btn btn-block btn-primary">
                           </div>
                    </form>
                 </div>
                    </div>
                </div>
              </div>
            </div>
        </div>
      </section>

        <!--Login and logout tab ends here-->

{% endblock content %}
    
   

gk/gkapp/templates/employee/guesthouseshw.html
{% extends "staffbase.html" %}
{% load static %}
{% load widget_tweaks %}
{% block content %}
   <div class="container-fluid">

                    <!-- DataTales Example -->
                    <div class="card shadow mb-4">
                        <div class="card-header py-3">
                            <h6 class="m-0 font-weight-bold text-primary">Guest House List</h6>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">

                                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                    <thead>
                                        <tr>
                                            <th>Name</th>
                                             <th>Actions</th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                            <th>Name</th>
                                             <th>Actions</th>
                                        </tr>
                                    </tfoot>
                                    <tbody>





{% for employee in employees %}
    <tr>
        <td>{{ employee.name }}</td>
        <td>
            <a class="btn btn-success" href="#"><span class="glyphicon glyphicon-pencil" >Edit</span></a>
            <a  class="btn btn-danger" href="#">Delete</a>

        </td>
    </tr>
{% endfor %}

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

                </div>
{% endblock content %}

gk/gkapp/templates/employee/reservation.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}
{% block content %}
<!--Cards starts here-->

        <!--login and signup tab starts here -->
        <section>
        <div class="container">
          <div class="row">
            <div class="col-md-6 mx-auto">
              <div class="card">
                <div class="card-header text-black">
                  <h2>Employee Signup</h2>
                </div>
                <div class="card-body">
                    <form action="{% url 'employee_signup' %}" method="POST" novalidate>
                      {% csrf_token %}
                         {% for field in form.visible_fields %}
                           <div class="form-group">
                               {{ field.label_tag }}
                                  {% render_field field class="form-control" %}
                                    {% for error in field.errors %}
                                      <span style="color:red">{{ error }}</span>
                                    {% endfor %}
                         {% endfor %}
                             <input type="submit" value="Register" class="btn btn-block btn-primary">
                           </div>
                    </form>
                 </div>
                    </div>
                </div>
              </div>
            </div>
        </div>
      </section>

        <!--Login and logout tab ends here-->

{% endblock content %}
    
   

gk/gkapp/templates/employee/rr.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Dependent Dropdown in Django</title>
</head>
<body>
<h2>Person Form</h2>

<form method="POST" action="{% url 'create_room_rate' %}">
  {% csrf_token %}
  {{ form.room_category_id }}
  {{ form.guest_category }}
  {{ form.rate }}
  <input type="submit" value="Submit">
</form>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
   <script>
  document.addEventListener("DOMContentLoaded", function () {
    const roomCategorySelect = document.querySelector("#id_room_category_id");
    const guestCategorySelect = document.querySelector("#id_guest_category");

    // Define a function to update the guest category options
    function updateGuestCategories() {
      const selectedRoomCategoryId = roomCategorySelect.value;
      // Make an AJAX request to fetch guest categories for the selected room category
      // Update the options in the guestCategorySelect element
    }

    // Attach an event listener to the roomCategorySelect element
    roomCategorySelect.addEventListener("change", updateGuestCategories);

    // Initialize the guest categories based on the initial room category (if needed)
    updateGuestCategories();
  });
</script>



</body>
</html>